apiVersion: v1
kind: Pod
metadata:
  name: web
  labels:
    app: nginx
    role: ui
    tier: front
spec:
  containers:
    - name: nginx
      image: schoolofdevops/nginx-synch
      ports:
        - containerPort: 80
      volumeMounts:
      - name: data
        mountPath: /var/www/html-sample-app
    - name: synch
      image: schoolofdevops/synch
      volumeMounts:
      - name: data
        mountPath: /var/www/html-sample-app
  volumes:
  - name: data
    emptyDir: {}
